import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import path from "node:path";

interface DocEntry {
  path: string;
  summary: string;
  readWhen: string[];
}

interface DocSection {
  heading: string;
  dir: string;
}

const SKIP_DIRS = new Set([
  ".git",
  ".next",
  "node_modules",
  "dist",
  "build",
  "__pycache__",
  ".waypoint",
]);

const SKIP_NAMES = new Set(["README.md", "CHANGELOG.md", "LICENSE.md"]);

function parseFrontmatter(filePath: string): { summary: string; lastUpdated: string; readWhen: string[] } {
  const text = readFileSync(filePath, "utf8");
  if (!text.startsWith("---\n")) {
    return { summary: "", lastUpdated: "", readWhen: [] };
  }

  const endIndex = text.indexOf("\n---\n", 4);
  if (endIndex === -1) {
    return { summary: "", lastUpdated: "", readWhen: [] };
  }

  const frontmatter = text.slice(4, endIndex);
  let summary = "";
  let lastUpdated = "";
  const readWhen: string[] = [];
  let collectingReadWhen = false;

  for (const rawLine of frontmatter.split("\n")) {
    const line = rawLine.trim();
    if (line.startsWith("summary:")) {
      summary = line.slice("summary:".length).trim().replace(/^['"]|['"]$/g, "");
      collectingReadWhen = false;
      continue;
    }
    if (line.startsWith("last_updated:")) {
      lastUpdated = line.slice("last_updated:".length).trim().replace(/^['"]|['"]$/g, "");
      collectingReadWhen = false;
      continue;
    }
    if (line.startsWith("read_when:")) {
      collectingReadWhen = true;
      continue;
    }
    if (collectingReadWhen && line.startsWith("- ")) {
      readWhen.push(line.slice(2).trim());
      continue;
    }
    if (collectingReadWhen && line.length > 0) {
      collectingReadWhen = false;
    }
  }

  return { summary, lastUpdated, readWhen };
}

function walkDocs(projectRoot: string, currentDir: string, output: DocEntry[], invalid: string[]): void {
  for (const entry of readdirSync(currentDir)) {
    const fullPath = path.join(currentDir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      if (SKIP_DIRS.has(entry)) {
        continue;
      }
      walkDocs(projectRoot, fullPath, output, invalid);
      continue;
    }

    if (!entry.endsWith(".md") || SKIP_NAMES.has(entry)) {
      continue;
    }

    const { summary, lastUpdated, readWhen } = parseFrontmatter(fullPath);
    const relPath = path.relative(projectRoot, fullPath);
    if (!summary || !lastUpdated || readWhen.length === 0) {
      invalid.push(relPath);
      continue;
    }
    output.push({ path: relPath, summary, readWhen });
  }
}

function collectDocEntries(projectRoot: string, docsDir: string): { entries: DocEntry[]; invalidDocs: string[] } {
  const entries: DocEntry[] = [];
  const invalidDocs: string[] = [];

  if (existsSync(docsDir)) {
    walkDocs(projectRoot, docsDir, entries, invalidDocs);
  }

  return { entries, invalidDocs };
}

export function renderDocsIndex(projectRoot: string, sections: DocSection[]): { content: string; invalidDocs: string[] } {
  const lines = [
    "# Docs Index",
    "",
    "Auto-generated by `waypoint sync` / `waypoint doctor`. Read matching docs and plans before working on a task.",
    "",
  ];
  const invalidDocs: string[] = [];

  for (const section of sections) {
    const { entries, invalidDocs: sectionInvalidDocs } = collectDocEntries(projectRoot, section.dir);
    invalidDocs.push(...sectionInvalidDocs);

    lines.push(`## ${section.heading}`);
    lines.push("");

    if (entries.length === 0) {
      lines.push("No routable docs found.");
    } else {
      for (const entry of entries.sort((a, b) => a.path.localeCompare(b.path))) {
        lines.push(`- **${entry.path}** — ${entry.summary}`);
        lines.push(`  Read when: ${entry.readWhen.join("; ")}`);
      }
    }

    lines.push("");
  }

  if (sections.length === 0) {
    lines.push("No routable docs found.");
  }

  return { content: `${lines.join("\n")}`, invalidDocs };
}
