import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import path from "node:path";

interface DocEntry {
  path: string;
  summary: string;
  readWhen: string[];
}

const SKIP_DIRS = new Set([
  ".git",
  ".next",
  "node_modules",
  "dist",
  "build",
  "__pycache__",
  ".waypoint",
]);

const SKIP_NAMES = new Set(["README.md", "CHANGELOG.md", "LICENSE.md"]);

function parseFrontmatter(filePath: string): { summary: string; readWhen: string[] } {
  const text = readFileSync(filePath, "utf8");
  if (!text.startsWith("---\n")) {
    return { summary: "", readWhen: [] };
  }

  const endIndex = text.indexOf("\n---\n", 4);
  if (endIndex === -1) {
    return { summary: "", readWhen: [] };
  }

  const frontmatter = text.slice(4, endIndex);
  let summary = "";
  const readWhen: string[] = [];
  let collectingReadWhen = false;

  for (const rawLine of frontmatter.split("\n")) {
    const line = rawLine.trim();
    if (line.startsWith("summary:")) {
      summary = line.slice("summary:".length).trim().replace(/^['"]|['"]$/g, "");
      collectingReadWhen = false;
      continue;
    }
    if (line.startsWith("read_when:")) {
      collectingReadWhen = true;
      continue;
    }
    if (collectingReadWhen && line.startsWith("- ")) {
      readWhen.push(line.slice(2).trim());
      continue;
    }
    if (collectingReadWhen && line.length > 0) {
      collectingReadWhen = false;
    }
  }

  return { summary, readWhen };
}

function walkDocs(projectRoot: string, currentDir: string, output: DocEntry[], invalid: string[]): void {
  for (const entry of readdirSync(currentDir)) {
    const fullPath = path.join(currentDir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      if (SKIP_DIRS.has(entry)) {
        continue;
      }
      walkDocs(projectRoot, fullPath, output, invalid);
      continue;
    }

    if (!entry.endsWith(".md") || SKIP_NAMES.has(entry)) {
      continue;
    }

    const { summary, readWhen } = parseFrontmatter(fullPath);
    const relPath = path.relative(projectRoot, fullPath);
    if (!summary || readWhen.length === 0) {
      invalid.push(relPath);
      continue;
    }
    output.push({ path: relPath, summary, readWhen });
  }
}

export function renderDocsIndex(projectRoot: string, docsDir: string): { content: string; invalidDocs: string[] } {
  const entries: DocEntry[] = [];
  const invalidDocs: string[] = [];

  if (existsSync(docsDir)) {
    walkDocs(projectRoot, docsDir, entries, invalidDocs);
  }

  const lines = [
    "# Docs Index",
    "",
    "Auto-generated by `waypoint sync` / `waypoint doctor`. Read matching docs before working on a task.",
    "",
    "## docs/",
    "",
  ];

  if (entries.length === 0) {
    lines.push("No routable docs found.");
  } else {
    for (const entry of entries.sort((a, b) => a.path.localeCompare(b.path))) {
      lines.push(`- **${entry.path}** — ${entry.summary}`);
      lines.push(`  Read when: ${entry.readWhen.join("; ")}`);
    }
  }

  lines.push("");
  return { content: `${lines.join("\n")}`, invalidDocs };
}

