import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import path from "node:path";

interface TrackEntry {
  path: string;
  summary: string;
  readWhen: string[];
  status: string;
}

const VALID_TRACK_STATUSES = new Set(["active", "blocked", "paused", "done", "archived"]);
const ACTIVE_TRACK_STATUSES = new Set(["active", "blocked", "paused"]);
const SKIP_NAMES = new Set(["README.md", "CHANGELOG.md", "LICENSE.md"]);

function shouldSkipTrackFile(entry: string): boolean {
  return SKIP_NAMES.has(entry) || entry.startsWith("_");
}

function parseFrontmatter(filePath: string): { summary: string; lastUpdated: string; readWhen: string[]; status: string } {
  const text = readFileSync(filePath, "utf8");
  if (!text.startsWith("---\n")) {
    return { summary: "", lastUpdated: "", readWhen: [], status: "" };
  }

  const endIndex = text.indexOf("\n---\n", 4);
  if (endIndex === -1) {
    return { summary: "", lastUpdated: "", readWhen: [], status: "" };
  }

  const frontmatter = text.slice(4, endIndex);
  let summary = "";
  let lastUpdated = "";
  let status = "";
  const readWhen: string[] = [];
  let collectingReadWhen = false;

  for (const rawLine of frontmatter.split("\n")) {
    const line = rawLine.trim();
    if (line.startsWith("summary:")) {
      summary = line.slice("summary:".length).trim().replace(/^['"]|['"]$/g, "");
      collectingReadWhen = false;
      continue;
    }
    if (line.startsWith("last_updated:")) {
      lastUpdated = line.slice("last_updated:".length).trim().replace(/^['"]|['"]$/g, "");
      collectingReadWhen = false;
      continue;
    }
    if (line.startsWith("status:")) {
      status = line.slice("status:".length).trim().replace(/^['"]|['"]$/g, "").toLowerCase();
      collectingReadWhen = false;
      continue;
    }
    if (line.startsWith("read_when:")) {
      collectingReadWhen = true;
      continue;
    }
    if (collectingReadWhen && line.startsWith("- ")) {
      readWhen.push(line.slice(2).trim());
      continue;
    }
    if (collectingReadWhen && line.length > 0) {
      collectingReadWhen = false;
    }
  }

  return { summary, lastUpdated, readWhen, status };
}

function walkTracks(projectRoot: string, currentDir: string, output: TrackEntry[], invalid: string[]): void {
  for (const entry of readdirSync(currentDir)) {
    const fullPath = path.join(currentDir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      walkTracks(projectRoot, fullPath, output, invalid);
      continue;
    }

    if (!entry.endsWith(".md") || shouldSkipTrackFile(entry)) {
      continue;
    }

    const { summary, lastUpdated, readWhen, status } = parseFrontmatter(fullPath);
    const relPath = path.relative(projectRoot, fullPath);
    if (!summary || !lastUpdated || readWhen.length === 0 || !VALID_TRACK_STATUSES.has(status)) {
      invalid.push(relPath);
      continue;
    }

    output.push({ path: relPath, summary, readWhen, status });
  }
}

export function renderTracksIndex(
  projectRoot: string,
  trackDir: string,
): { content: string; invalidTracks: string[]; activeTrackPaths: string[] } {
  const entries: TrackEntry[] = [];
  const invalidTracks: string[] = [];

  if (existsSync(trackDir)) {
    walkTracks(projectRoot, trackDir, entries, invalidTracks);
  }

  const lines = [
    "# Tracks Index",
    "",
    "Auto-generated by `waypoint sync` / `waypoint doctor`. Read active trackers when resuming long-running work.",
    "",
    "## .waypoint/track/",
    "",
  ];

  if (entries.length === 0) {
    lines.push("No tracker files found.");
  } else {
    for (const entry of entries.sort((a, b) => a.path.localeCompare(b.path))) {
      lines.push(`- **${entry.path}** — [${entry.status}] ${entry.summary}`);
      lines.push(`  Read when: ${entry.readWhen.join("; ")}`);
    }
  }

  lines.push("");

  return {
    content: `${lines.join("\n")}`,
    invalidTracks,
    activeTrackPaths: entries
      .filter((entry) => ACTIVE_TRACK_STATUSES.has(entry.status))
      .map((entry) => entry.path)
      .sort((a, b) => a.localeCompare(b)),
  };
}
